### ISSUE TITLE
I keep getting errors when using array_map

### ISSUE THREAD

**Issue by Nightflyyer** [kvz/locutus#277] opened 2016-02-01 19:52 UTC
I keep getting TypeError: Cannot read property 'length' of undefined

**Comment by AdityaSinghChauhan** [comment] 2016-02-26 19:50
This must be because the object that you are trying to access does not exist. Firstly, check for any spelling error in the object name and then check if at all the object exists. 
You also can try Object.keys(myObject).length for objects do not have .length property.

**Comment by kvz** [comment] 2016-05-21 20:26
Thanks for reporting but we were unable to gather enough info so I'll be closing this issue for now. Feel free to re-open with steps to reproduce.

**Closed by kvz** 2016-05-21 20:26 UTC
Labels: need-more-info
