### ISSUE TITLE
Unserialize throws error

### ISSUE THREAD

**Issue by IngwiePhoenix** [kvz/locutus#190] opened 2014-09-24 21:28 UTC
I was going to try out to parse a real-world example of a serialized object. However, I got the following output:

```
> php.unserialize
[Function]
> php.unserialize( 'a:2:{i:0;a:2:{i:0;a:3:{i:0;O:8:"CUrlRule":16:{s:9:"urlSuffix";N;s:13:"caseSensitive";N;s:13:"defaultParams";a:0:{}s:10:"matchValue";N;s:4:"verb";N;s:11:"parsingOnly";b:0;s:5:"route";s:17:"<controller>/view";s:10:"references";a:1:{s:10:"controller";s:12:"<controller>";}s:12:"routePattern";s:30:"/^(?P<controller>\w+)\/view$/u";s:7:"pattern";s:39:"/^(?P<controller>\w+)\/(?P<id>\d+)\/$/u";s:8:"template";s:17:"<controller>/<id>";s:6:"params";a:1:{s:2:"id";s:3:"\d+";}s:6:"append";b:0;s:11:"hasHostInfo";b:0;s:14:"}' );
TypeError: undefined is not a function
    at error (/Users/Ingwie/Work/BIRD3/node_modules/phpjs/build/npm.js:8548:13)
    at _unserialize (/Users/Ingwie/Work/BIRD3/node_modules/phpjs/build/npm.js:8676:11)
    at _unserialize (/Users/Ingwie/Work/BIRD3/node_modules/phpjs/build/npm.js:8655:22)
    at _unserialize (/Users/Ingwie/Work/BIRD3/node_modules/phpjs/build/npm.js:8655:22)
    at _unserialize (/Users/Ingwie/Work/BIRD3/node_modules/phpjs/build/npm.js:8655:22)
    at Object.exports.unserialize (/Users/Ingwie/Work/BIRD3/node_modules/phpjs/build/npm.js:8682:12)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
```

Why am I getting that?

**Comment by kvz** [comment] 2016-05-21 21:00
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/).

It seems our unserialize function needs some love. @kukawski I noticed you self-assigned this one, did you have plans to attack it?

**Comment by kukawski** [comment] 2016-05-21 21:22
@kvz yes, I plan to work on it. Currently I'm on strtotime rewrite, but I will probably change focus to this one as this problem is simpler to fix.

**Comment by kvz** [comment] 2016-05-22 11:52
Awesome 💯

**Comment by kukawski** [comment] 2016-06-05 19:55
I don't get the same error message about trying to call undefined as function with latest locutus release. The only problem with the example call is, that it has a serialized object ("O" type) which is currently unhandled. I will look at past commits to understand why we don't support this type and eventually try to implement it.

**Comment by kukawski** [comment] 2017-05-05 11:30
The problem with "O" type is, that it is followed by class name. The name may also include namespace. PHP can serialize and deserialize private and protected object properties, which then get special markup included in the serialized string. JS doesn't have private and protected properties nor real namespaces, thus implementing "O" is only partially possible. Just throwing error on "O" with the message we currently have is IMHO a better way than do lots of logic to be able to handle the type only partially.

Anyway, I can't reproduce the original issue, so I will close the ticket. If the issue still exists, please reopen and include a new example for reproduction.

**Closed by kukawski** 2017-05-05 11:30 UTC
Labels: needs-attention
